// This file is auto-generated by @hey-api/openapi-ts

export const $bad_request = {
    description: 'Bad request model',
    properties: {
        error: {
            description: 'Bad request message',
            type: 'string'
        }
    },
    required: ['error'],
    title: 'Bad request',
    type: 'object'
} as const;

export const $error_limited = {
    description: 'Error limited model',
    properties: {
        error: {
            description: 'Error limited message',
            type: 'string'
        }
    },
    required: ['error'],
    title: 'Error limited',
    type: 'object'
} as const;

export const $forbidden = {
    description: 'Forbidden model',
    properties: {
        error: {
            description: 'Forbidden message',
            type: 'string'
        },
        sso_status: {
            description: 'status code received from SSO',
            type: 'integer'
        }
    },
    required: ['error'],
    title: 'Forbidden',
    type: 'object'
} as const;

export const $gateway_timeout = {
    description: 'Gateway timeout model',
    properties: {
        error: {
            description: 'Gateway timeout message',
            type: 'string'
        },
        timeout: {
            description: 'number of seconds the request was given',
            type: 'integer'
        }
    },
    required: ['error'],
    title: 'Gateway timeout',
    type: 'object'
} as const;

export const $internal_server_error = {
    description: 'Internal server error model',
    properties: {
        error: {
            description: 'Internal server error message',
            type: 'string'
        }
    },
    required: ['error'],
    title: 'Internal server error',
    type: 'object'
} as const;

export const $service_unavailable = {
    description: 'Service unavailable model',
    properties: {
        error: {
            description: 'Service unavailable message',
            type: 'string'
        }
    },
    required: ['error'],
    title: 'Service unavailable',
    type: 'object'
} as const;

export const $unauthorized = {
    description: 'Unauthorized model',
    properties: {
        error: {
            description: 'Unauthorized message',
            type: 'string'
        }
    },
    required: ['error'],
    title: 'Unauthorized',
    type: 'object'
} as const;